const MaintenanceTicket = require('../models/MaintenanceTicket');
const Device = require('../models/Device');

// Initialize Socket.IO
let io;

// Function to set Socket.IO instance
const setSocketIO = (socketIO) => {
  io = socketIO;
};

const MaintenanceController = {
  // Get all maintenance tickets with optional filters
  async getAllTickets(req, res) {
    try {
      const { status, severity, building } = req.query;
      
      // Build filter object based on query parameters
      const filter = {};
      if (status) filter.status = status;
      if (severity) filter.severity = severity;
      if (building) filter.building = building;

      const tickets = await MaintenanceTicket.find(filter)
        .sort({ createdAt: -1 }) // Newest first
        .lean();

      // Get device details for each ticket
      const ticketsWithDeviceDetails = await Promise.all(
        tickets.map(async (ticket) => {
          if (ticket.deviceId) {
            const device = await Device.findOne({ deviceId: ticket.deviceId });
            return { ...ticket, device };
          }
          return ticket;
        })
      );

      res.json(ticketsWithDeviceDetails);
    } catch (error) {
      console.error('Error fetching maintenance tickets:', error);
      res.status(500).json({ error: 'Failed to fetch maintenance tickets' });
    }
  },

  // Create a new maintenance ticket manually
  async createTicket(req, res) {
    try {
      const { deviceId, building, issueType, severity = 'Medium', description } = req.body;
      
      // Validate required fields
      if (!deviceId || !building || !issueType) {
        return res.status(400).json({ error: 'Missing required fields' });
      }

      // Check if device exists
      const device = await Device.findOne({ deviceId });
      if (!device) {
        return res.status(404).json({ error: 'Device not found' });
      }

      // Create new ticket
      const ticket = new MaintenanceTicket({
        deviceId,
        building,
        issueType,
        severity,
        description,
        status: 'Pending'
      });

      await ticket.save();

      // Emit Socket.IO event
      if (io) {
        io.emit('newMaintenanceTicket', ticket);
      }

      res.status(201).json(ticket);
    } catch (error) {
      console.error('Error creating maintenance ticket:', error);
      res.status(500).json({ error: 'Failed to create maintenance ticket' });
    }
  },

  // Resolve a maintenance ticket
  async resolveTicket(req, res) {
    try {
      const { id } = req.params;
      
      const ticket = await MaintenanceTicket.findById(id);
      if (!ticket) {
        return res.status(404).json({ error: 'Ticket not found' });
      }

      ticket.status = 'Resolved';
      ticket.resolvedAt = new Date();
      await ticket.save();

      // Emit Socket.IO event
      if (io) {
        io.emit('ticketResolved', ticket);
      }

      res.json(ticket);
    } catch (error) {
      console.error('Error resolving maintenance ticket:', error);
      res.status(500).json({ error: 'Failed to resolve maintenance ticket' });
    }
  },

  // Automatically create ticket based on conditions
  async autoCreateTicket(ticketData) {
    try {
      const { deviceId, building, issueType, severity = 'Medium', description } = ticketData;
      
      if (!deviceId || !building || !issueType) {
        throw new Error('Missing required fields for auto ticket creation');
      }

      // Check for existing similar pending tickets
      const existingTicket = await MaintenanceTicket.findOne({
        deviceId,
        issueType,
        status: 'Pending'
      });

      if (existingTicket) {
        console.log('Similar ticket already exists:', existingTicket.ticketId);
        return existingTicket;
      }

      // Create new ticket
      const ticket = new MaintenanceTicket({
        deviceId,
        building,
        issueType,
        severity,
        description: description || `Automatically generated ticket for ${issueType}`,
        status: 'Pending',
        isAutoGenerated: true
      });

      await ticket.save();

      // Emit Socket.IO event
      if (io) {
        io.emit('newMaintenanceTicket', ticket);
      }

      console.log(`Auto-created maintenance ticket: ${ticket.ticketId}`);
      return ticket;
    } catch (error) {
      console.error('Error in autoCreateTicket:', error);
      throw error;
    }
  },

  // Set Socket.IO instance
  setSocketIO
};

module.exports = MaintenanceController;
